#! /usr/bin/env perl
use strict;
#
# Neutralise date/time expressions.
#
while (<>) {
    #
    # First get rid of the times
    #
    s§ \b\d{2}:\d{2}:\d{2}\s+[[:alpha:]]{3}      §XX:XX:XX XXX§gx;
    s§ \b\d{2}:\d{2}:\d{2}\b                     §XX:XX:XX§gx;
    s§ \b\d{2}H\d{2}\b                           §XX:XX§gix;
    #
    # Now some date formats.
    #
    s§ XXX\s\d{4}\b                              §XXX XXXX§gx;
    s§ \b\d{4}-\d{2}-\d{2}\b                     §XXXX-XX-XX§gx;
    s§ \b[[:alpha:]]{3}\s[[:alpha:]]{3}\s\d{2}\b §XXX XXX XX§gx;
    print $_;
}

#
# Local Variables:
# mode: cperl
# tab-width: 4
# indent-tabs-mode: nil
# End:
#
